### ISSUE TITLE
problem with readme.md

### ISSUE THREAD

**Issue by alirezafour** [MehrdadLinux/MehrdadLinux.github.io#1]
dear Mrhrdadlinux

hello, I have questions. 
how I can create a post and manage that? 
do I need an application? 
can you complete your readme.md?

**Comment by MehrdadLinux** [comment]
Hi
To create a new post, all you need to do is create a new file in the _posts directory
How you name files in this folder is important. this bps  requires blog post files to be named according to the following format:
YEAR-MONTH-DAY-title.MARKUP
Where YEAR is a four-digit number, MONTH and DAY are both two-digit numbers, and MARKUP is the file extension representing the format used in the file. For example, the following are examples of valid post filenames:
2011-12-31-new-years-eve-is-awesome.md
2012-09-12-how-to-write-a-blog.textile
Sincerely Yours,
MehrdadLinux
